[build]
  base = "apps/web"
  command = "npx next build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"
  NEXTAUTH_SECRET = "${NEXTAUTH_SECRET}"

[[plugins]]
  package = "@netlify/plugin-nextjs"
